= Cheng Xianhao - Project Portfolio
:site-section: AboutUs
:toc:
:toc-title:
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Health Book

---

== Overview

Health Book is a desktop address book application targeted at health care professionals who seek to retrieve their patients' personal details and health-related information all in one place.
The application provides both a Command Line Interface (CLI) for input of data and a Graphical User Interface (GUI) for displaying of output (patient's personal details and health-related information).
The application is fully written in Java, allowing cross-platform compatibility.

== Summary of contributions

* *Major enhancement*: Added *the ability to add/edit additional information*.
** What it does: Allows users to selectively add or edit additional information of patients that are not required for the creation of a patient profile in Health Book.
** Justification: Based on the team's interview with health care professionals, the team understood that some of the information that health care professionals are interested about their patients include bio-data like NRIC, gender, blood type, occupation, height and weight which might not be available upon the creation of the patient's profile. Giving the user the ability to add or edit such information after the creation of patient profile provides user with more flexibility on managing such information.
** Highlights: To ensure that users input the correct type of data for the correct type of information, a dual-layer check system is implemented for most fields - the first layer is done by using Java Regular Expressions, while the second layer is done using checksum algorithms and exception handling. The different types of information to be added means that an iterative approach has to be taken. However, this would also mean that care needs to be taken to ensure that there are no regression.

* *Minor enhancement*:
** Presented the additional information in a table view format in the main window.
*** Justification: Health care professionals interact with such information frequently. A table view format is best able to present these information in a systematic manner.
** Toggleable encryption with AES 128-bit symmetric encryption
*** Justification: As the application is targeted at the health care industry where privacy is of major concern, encryption is the solution to ensure that the application remains socially responsible. However, to handle the project constraint of "human-editable-file", the encryption functionality is a toggled feature so that user can choose to disable encryption should they require the human-editable saved data.
*** Credits: http://santuario.apache.org/[Apache Santuario]'s encryption library is used for this feature.

* *Code contributed*: https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=xhxh96[CodeDashboard]

* *Other contributions*:

**  Role of Domain Expert:
*** In-charged of gathering user requirements
*** In-charged of managing version control system workflow
** Project management:
*** Managed the use of issue tracker and kanban board.
*** Managed the use of Continuous Integration tools.
*** Designed the workflow for using of GitHub
** Enhancements to existing features:
*** Increased code coverage from 78% to 82% (Pull requests https://github.com/CS2113-AY1819S1-T12-2/main/pull/213[#213])
** Tools:
*** Integrated AppVeyor and Coverall.
** Community:
*** PRs review with non-trivial comments:
*** Reported bugs and suggestions for other teams in class(Issue https://github.com/CS2113-AY1819S1-T16-2/main/issues/103[#103], https://github.com/CS2113-AY1819S1-T16-2/main/issues/93[#93], https://github.com/CS2113-AY1819S1-T16-2/main/issues/98[#98])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addinfocommands]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=addinfo]

include::../DeveloperGuide.adoc[tag=dataencryption]

include::../DeveloperGuide.adoc[tag=addinfousecase]

include::../DeveloperGuide.adoc[tag=dataencryptionusecase]

