= Hovan Tan - Project Portfolio
:site-section: AboutUs
:toc:
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets

[discrete]
== PROJECT: HealthBook

---

== Overview

* *Abstract* +
HealthBook is an address book application that is catered for healthcare professionals who seek to retrieve their patients’ personal information and health-related information all in one place. Command Line Interface (CLI) is utilized mainly for the input, while the Graphical User Interface (GUI) is used mainly to display the output. By combining these 2 interfaces, Health Book aims to provide healthcare professionals with the speed and efficiency obtained from a CLI while retaining the systematic view of information through the GUI.

* *The Problem* +
Every member in the team has faced long queues in a clinic or hospital before. Our aim is to speed up this process by tackling the admin process. +
Personal Experience: Doctor visits were prolonged unnecessarily where doctors spent more time fiddling with their current health systems, trying to key in prescriptions and to update medical records, instead of attending to me, the patient.

* *The Solution* +
We decided to use an existing addressbook application that has the basic functionalities to store people and their personal information and upgrade it to be used in the medical field. +
HealthBook would be considered an all-in-one application that allows doctors to view medical reports, medical histories, medical appointments and enhanced details of each patient. All of this while maintaining a minimalistic user interface for the aims of making the application user-friendly.

* *The Features* +
1. Additional Information: Allows healthcare professionals to enter and edit optional details of the patients such as nric and blood type for easier classification.

2. Medical History: Allows healthcare professionals to enter and edit patient's medical history with parameters such as allergy and discharge status which helps identify past health concerns and predict future health trends.

3. Medical Appointment: Allows healthcare professionals to enter and edit patient's appointments and can be accessed easily.

4. Medical Reports: Allows healthcare professionals to enter and edit multiple detailed medical reports of past visits with a title to make it easier to locate key illnesses and aids the prescription process.

5. Find and Sort: Allows healthcare professionals to not only sort and find patients by name, but also by medical parameters such as blood type and allergy. This quickens the administrative process by locating the patient faster.

HealthBook prides itself in being a minimalistic application with reduced clutter such that healthcare professionals are able to view key details of patients without unnecessary visual noise.

The development of HealthBook is led by a 5-man team consisting of a Project Manager, Design Lead, Development Lead, Quality Assurance Lead and Subject Matter Expert.
My role in this project is the Project Manager, overseeing the weekly progress of the team and constant communication among members.

== Summary of contributions

|===
|_This section below lists my contributions in this project which includes both code contributions and team contributions.
The following portrays my ability to code and enhance an application while still being a team player and leader._
|===

* *Major enhancement*: added *the ability to add and edit medical history entries for a patient.*
** What it does: allows the user to key in major medical changes and events of a patient on a certain date.
** Justification: This feature helps medical professionals by using past diseases, family history and many other variables to predict future health trends and provide medical advice.
** Highlights: Apart from the date being compulsory, all other variables are optional in case they do not need to be updated. The user interface is minimalistic and user-friendly to prevent clutter of information.
** Credits: Optional code syntax was adopted from EditCommand.

* *Code contributed:*
** [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=xshaivan&sort=displayName&since=2018-09-12&until=2018-11-04&timeframe=day&reverse=false&repoSort=true[Reposense collated code]]

* *Other contributions*:

** Project Management:
*** Role: Project Manager
*** Managed weekly deadlines and handled distribution of workload throughout the project timeline.
*** Acted as team's secretary, scheduling meetings and agenda while taking down meeting minutes and notes during these sessions.
*** Acted as team mediator and middleman, facilitated smooth flow and exchange of ideas. Also helped resolve conflicts within team for better productivity.

** Documentation:
*** Helped with introducing of ideas for user stories in the initial stage.
*** Helped with listing non-functional requirements in the initial stage.
*** Helped proofread documentation to ensure readability and relevance with the HealthBook application.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addhist]

include::../UserGuide.adoc[tag=edithist]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=addhist]
include::../DeveloperGuide.adoc[tag=edithist]
